---
# tasks file for ansible-role-docker-container-reposilite

- name: docker_image pull {{ docker_image_reposilite_name }}
  community.docker.docker_image:
    name: '{{ docker_image_reposilite_name }}'
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: amd64
  when: 
    - docker_image_reposilite_pull

- name: docker_network {{ docker_container_reposilite_name }}
  community.docker.docker_network:
    name: "{{ docker_network_reposilite_name }}"
    driver: "{{ docker_network_reposilite_driver | default('bridge') }}"
    attachable: "{{ docker_network_reposilite_attachable | default('yes') }}"
    enable_ipv6: "{{ docker_network_reposilite_enable_ipv6 | default('no') }}"
    internal: "{{ docker_network_reposilite_internal | default('no') }}"
    state: present


- name: docker_container {{ docker_container_reposilite_name }}
  community.docker.docker_container:
    name: "{{ docker_container_reposilite_name }}"
    comparisons: "{{ docker_container_reposilite_comparisons }}"
    image: "{{ docker_container_reposilite_image }}"
    state: "{{ docker_container_reposilite_state | default('started') }}"
    recreate: "{{ docker_container_reposilite_recreate | default('no') }}"
    restart: "{{ docker_container_reposilite_restart | default('no') }}"
    restart_policy: "{{ docker_container_reposilite_restart_policy | default('always') }}"
    container_default_behavior: no_defaults
    auto_remove: "{{ docker_container_reposilite_auto_remove | default('no') }}"
    detach: "{{ docker_container_reposilite_detach | default('yes') }}"
    init: "{{ docker_container_reposilite_init | default('no') }}"
    interactive: "{{ docker_container_reposilite_interactive | default('no') }}"
    keep_volumes: "{{ docker_container_reposilite_keep_volumes | default('yes') }}"
    memory: "{{ docker_container_reposilite_memory | default('0') }}"
    paused: "{{ docker_container_reposilite_paused | default('no') }}"
    privileged: "{{ docker_container_reposilite_privileged | default('no') }}"
    read_only: "{{ docker_container_reposilite_read_only | default('no') }}"
    tty: "{{ docker_container_reposilite_tty | default('no') }}"
    env_file: "{{ docker_container_reposilite_env_file | default(omit) }}"
    env: "{{ docker_container_reposilite_env | default(omit) }}"
    volumes: "{{ docker_container_reposilite_volumes | default(omit) }}"
    labels: "{{ docker_container_reposilite_labels | default(omit) }}"
    networks_cli_compatible: "{{ docker_container_reposilite_networks_cli_compatible | default('yes') }}"
    network_mode: "{{ docker_network_reposilite_name }}"
    pull: "{{ docker_container_reposilite_pull | default('no') }}"
    networks: "{{ docker_container_reposilite_networks }}"
    published_ports: "{{ docker_container_reposilite_ports | default(omit) }}"
